version: 2.1
jobs:
  build-test:
    docker:
      - image: circleci/node:14
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
    
      - run:
          name: Install Dependencies
          command: npm install
    
      - run:
          name: npm Audit Fix
          command: npm audit fix

      - run:
          name: npm Audit for Critical Vulnerabilities
          command: npm audit --audit-level=critical
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
    
      - run:
          name: Run Tests
          command: npm run test
    
      - run:
          name: Build Project
          command: npm run build

workflows:
  node-tests:
    jobs:
      - build-test
